### PR TITLE
PTS: Add setting to display temperature in Fahrenheit

### LINKED ISSUE #1783: Weather: temp won't display in Fahrenheit
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

Weather only reports in Celsius

### What should happen instead?

When specified, weather should report in Fahrenheit

### Reproduction steps

I am using Gadgetbridge (0.74.0) with the QuickWeather (2.3.2) app on Android. GadgetBridge is configured for Imperial and QuickWeather is configured for Fahrenheit. My family all have PineTimes running InfiniTime 1.13.0 and they are displaying the temperature in Celsius.

### More details?

I do not see any relevant issues reported for either of their apps. A quick look through their repositories did not lead me to believe the issue was elsewhere, especially because PineTime recently implemented weather functionality. Though, I could absolutely be incorrect and apologize in advance if that is the case.

Has anyone seen Fahrenheit temperatures using the new weather feature?

### Version

1.13.0

### Companion app

Gadgetbridge 0.74.0

### PR DESCRIPTION
**Pull request by FintasticMan**
This adds a "weather format" setting, which can be either Metric or Imperial.

Fixes #1783.

@kieranc does this look good to you?

### CODE REVIEW

**Comment by JF002** [comment]
@FintasticMan Thanks for this PR! I usually refrain from adding new settings but I think we cannot avoid this one : the world use 2 units to measure the temperature, we need to adapt :-)

Would you like to port those changes to the new Simple Weather Service implementation (https://github.com/InfiniTimeOrg/InfiniTime/pull/1924) ? We'll probably merge it soon.

**Comment by FintasticMan** [comment]
Yes, I'll rebase this onto #1924 👍

File: src/components/ble/SimpleWeatherService.h [hunk 1]
```diff
@@ -0,0 +1,143 @@
...
+          Icons iconId;
+        };
+
+        std::array<Day, MaxNbForecastDays> days;
+      };
+
+      std::optional<CurrentWeather> Current() const;
+      std::optional<Forecast> GetForecast() const;
+
+      static constexpr int16_t CelsiusToFahrenheit(int16_t celsius);
```
Comment (JF002) [inline src/components/ble/SimpleWeatherService.h:107]: I don't think we need `constexpr` here, the function will most probably be evaluated at runtime anyway.

Comment (FintasticMan) [reply src/components/ble/SimpleWeatherService.h]: We don't need it, you're right, but there's no harm in adding it.

Comment (JF002) [reply src/components/ble/SimpleWeatherService.h]: In my opinion, `constexpr` adds some semantic to the code, it tells the reader that this method returns a constant value that might be computed at compile time. But this is not the case for this method : it can only be evaluated at runtime, and the `const` semantic does not apply here either.

I was a bit confused when I read it, so I think it would be better to remove it, if that's ok for you.

**Review by JF002 — COMMENTED** [review]
Thanks, we'll merge this one after https://github.com/InfiniTimeOrg/InfiniTime/pull/1924 :)
