### PR TITLE
Prevents blocking when Infineat watchface is charging

### LINKED ISSUE #2245: Return to Infineat watch face crashes when charging
### Verification

- [x] I searched for similar bug reports (including closed issues) and found none was relevant.

### What happened?

Swip off Infineat watch face, placing on charger, wait for screen to go blank and pressing button twice, screen remains blank and resets watchdog

### What should happen instead?

Watch should not crash. It should display the watchface when you press the button (which it does for all watch faces except Infineat)

### Reproduction steps

Display timeout is 5 secs.
Only happens with the Infineat face
Go through the below quite quickly.
Reproduced 100% of the time.

Swipe watchface to access quick settings
Place on charger
Small charge icon is displayed at top of display
Display switches off after 5 seconds
Press button to switch on display (I wanted to be sure it was charging)
Display doesn't switch on*
Press button again.
Display doesn't switch on.
Remove from charger
Press button to switch on Display
Watchdog timeout occurs
See watchface for a fraction of a second and then white to green pine cone
Last reset = wtdg

### More details?

No shake to wake
Backlight low, med, high
24h
Infineat (works as expected on other faces)
Display timeout 5s
Bluetooth connected or off
Not using weather reporting
Watch is 5 years old from hardware point of view.
Battery level was <50% when I first noticed this and was reproduced multiple times at 100% charge.
Button presses were quick clicks. i.e. I didn't hold the button for 7 seconds to force a watchdog timer reset.

### Version

Standard V1.15 2105a7b6

### Companion app

_No response_

### PR DESCRIPTION
**Pull request by SteveAmor**
This PR prevents the blocking issue identified in #2245 
This is a better solution than the one proposed in #2248

### CODE REVIEW

**Comment by SteveAmor** [comment]
I'm all for clean code and keeping things tidy but I don't like the way clang wants to right justify my comment, about the magic number 3, with the previous charging battery animation comment.
```(lv_tick_get() - savedAnimationTick > 150)) { // Charging battery animation```
```chargingBatteryPercent += 3;                  // 100% / pine_small height = 3```
But, if I have to make the change I will.

File: src/displayapp/screens/WatchFaceInfineat.cpp [hunk 1]
```diff
@@ -434,12 +434,13 @@ void WatchFaceInfineat::Refresh() {
 
   batteryPercentRemaining = batteryController.PercentRemaining();
   isCharging = batteryController.IsCharging();
-  if (batteryController.IsCharging()) { // Charging battery animation
-    chargingBatteryPercent += 1;
+  if (batteryController.IsCharging() && (lv_tick_get() - savedAnimationTick > 150)) { // Charging battery animation
```
Comment (NeroBurner) [inline src/displayapp/screens/WatchFaceInfineat.cpp:437]: What happens when the tick counter wrapps around. Then the tick count is smaller than the saved tick count. What would be the resulting behaviour?

Comment (SteveAmor) [reply src/displayapp/screens/WatchFaceInfineat.cpp:437]: Good point. I need to add a cast to fix this ```(uint32_t(lv_tick_get() - savedAnimationTick) > 150)```

Comment (SteveAmor) [reply src/displayapp/screens/WatchFaceInfineat.cpp]: > Good point. I need to add a cast to fix this `(uint32_t(lv_tick_get() - savedAnimationTick) > 150)` Now, wrap around shouldn't be a problem.

I tested on the simulator with and without the ```uint32_t``` and the compiler applies the same modulo arithmetic for unsigned ints to either version with no change in the complied flash and ram sizes. However, it's probably safer to leave ```uint32_t``` in.

File: src/displayapp/screens/WatchFaceInfineat.cpp [hunk 2]
```diff
@@ -434,12 +434,13 @@ void WatchFaceInfineat::Refresh() {
 
   batteryPercentRemaining = batteryController.PercentRemaining();
   isCharging = batteryController.IsCharging();
-  if (batteryController.IsCharging()) { // Charging battery animation
-    chargingBatteryPercent += 1;
+  if (batteryController.IsCharging() && (uint32_t(lv_tick_get() - savedAnimationTick) > 150)) { // Charging battery animation
+    chargingBatteryPercent += 3; // 100% / pine_small height = 3
```
[the remark this answers is not in the document]
Comment (SteveAmor) [reply src/displayapp/screens/WatchFaceInfineat.cpp]: Thanks for the feedback @mark9064. I have made the changes and it works as expected in terms of the same timings as the original code and as per the first commit in this PR.
Let me know if any more changes are required.  If not, would you would like me to squash the commits?

File: src/displayapp/screens/WatchFaceInfineat.cpp [hunk 3]
```diff
@@ -434,12 +434,13 @@ void WatchFaceInfineat::Refresh() {
 
   batteryPercentRemaining = batteryController.PercentRemaining();
   isCharging = batteryController.IsCharging();
-  if (batteryController.IsCharging()) { // Charging battery animation
-    chargingBatteryPercent += 1;
+  if (batteryController.IsCharging() && (uint32_t(lv_tick_get() - savedAnimationTick) > 150)) { // Charging battery animation
```
[the remark this answers is not in the document]
Comment (SteveAmor) [reply src/displayapp/screens/WatchFaceInfineat.cpp]: Thanks for the feedback @mark9064. I have made the changes and it works as expected in terms of the same timings as the original code and as per the first commit in this PR.

File: src/displayapp/screens/WatchFaceInfineat.h [hunk 4]
```diff
@@ -46,6 +46,7 @@ namespace Pinetime {
 
       private:
         uint32_t savedTick = 0;
+        uint32_t savedAnimationTick = 0;
```
[the remark this answers is not in the document]
Comment (SteveAmor) [reply src/displayapp/screens/WatchFaceInfineat.h]: I think/hope the changes I made address this?

**Comment by SteveAmor** [comment]
@mark9064 let me know if any more changes are required.  If not, would you would like me to squash the commits?

File: src/displayapp/screens/WatchFaceInfineat.cpp [hunk 5]
```diff
@@ -434,12 +434,13 @@ void WatchFaceInfineat::Refresh() {
 
   batteryPercentRemaining = batteryController.PercentRemaining();
   isCharging = batteryController.IsCharging();
-  if (batteryController.IsCharging()) { // Charging battery animation
-    chargingBatteryPercent += 1;
+  if (batteryController.IsCharging() && (xTaskGetTickCount() - chargingAnimationTick > pdMS_TO_TICKS(150))) { // Charging battery animation
+    chargingBatteryPercent += 100 / lv_obj_get_height(logoPine);
```
Comment (mark9064) [inline src/displayapp/screens/WatchFaceInfineat.cpp:438]: I think a code comment here to explain what is going on would be good (dividing 100 by the height means we can find the battery percentage change needed to shift the indicator by 1 pixel)

Comment (SteveAmor) [reply src/displayapp/screens/WatchFaceInfineat.cpp]: Hopefully done 😀

Comment (mark9064) [reply src/displayapp/screens/WatchFaceInfineat.cpp]: Maybe pop the comment the line before rather than inline? Might be easier to read that way

**Comment by SteveAmor** [comment]
Thank you for your patience. I have been battling the clang formatting to get the test to pass. I always wanted to move the comment above the line of code.

File: src/displayapp/screens/WatchFaceInfineat.cpp (hunk 5 above)
Comment (SteveAmor) [reply src/displayapp/screens/WatchFaceInfineat.cpp:440]: Thank you for your patience. I have been battling the clang formatting to get the test to pass. I always wanted to move the comment above the line of code.

**Review by mark9064 — APPROVED** [review]
Thanks for the report and fix!

I think this is good to go, my only criticism would be is that when it's almost full the battery indicator might flicker in some way. But I think it did this before, so it's not a regression. How has it looked in your testing?

**Comment by SteveAmor** [comment]
> I think this is good to go, my only criticism would be is that when it's almost full the battery indicator might flicker in some way. But I think it did this before, so it's not a regression. How has it looked in your testing?

On the PT hardware, it looks identical to the animation in V1.15 and the animation when the battery is almost full is also the same. It's quite tolerable, not flashing the last pixel or two too fast. You can see it's charging when you're at 90+ percent.
