### PR TITLE
Unconditionally update motion

### LINKED ISSUE #787: Step counter doesn't start on new day
### 

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

Step counter doesn't start counting after 12AM unless watch is awaken

### What should happen instead?

Even if you don't wake the watch it should start counting.

### Reproduction steps

- Setup your watch to wake up with single or double tap
- Wait for time to pass 12:00AM
- Without waking up the watch (either by single, double or pressing the button), start walking
- After few steps wake the watch and see if the steps counter is still zero.

### More details?

The counter will work if you have the wake up setting to Raise Wrist.

### Version

v1.6.0

### Companion app

n/a

### LINKED ISSUE #1270: InfiniTime sends Steps count from the previous day in some cases
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

InfiniTime sends Steps count from the previous day in some cases

### What should happen instead?

InfiniTime should count from 0 after midnight

### Reproduction steps

so far there are 2 cases discovered where InfiniTime sends wrong steps count to Step count characteristic subscriber (e.g. companion app Gadgetbridge):

**case 1**
1. make some steps (e.g. 1000 steps) on day 1.
2. unlock PineTime before midnight to make sure steps are synced.
3. after the midnight (e.g. in the morning) receive notification to the PineTime (e.g. incoming call, or use "fing lost device" in Gadgetbridge)
4. InfiniTime sends step count from the previous day (1000 steps in this case) before reset the steps counter. that won't happen if you just unlock the PineTime. it's specifically related to the case with notification.

**case 2** (probable the issue #787. see [this comment](https://github.com/InfiniTimeOrg/InfiniTime/issues/787#issuecomment-1209173778))
1. make some steps (e.g. 1000 steps) on day 1.
2. unlock PineTime before midnight to make sure steps are synced.
3. after the midnight (e.g. in the morning or overnight) make some steps (e.g. 50 steps) **without** unlocking PineTime.
4. unlock PineTime, and it will send 2 steps count in less that a second: 
   - 1st one - combined values from previous day plus outstanding steps from the new day (1000 + 50 -> 1050steps)
   - 2nd one - zeroed value (literally "0"). also InfiniTime  displays "0" steps. that means all steps from the day 2 before the unlock (50 steps) are gone/zeroed. 

### More details?

there is a discussion about that issues and workaround on Gadgetbridge side ([Gadgetbridge#2783](https://codeberg.org/Freeyourgadget/Gadgetbridge/issues/2783)).

### Version

1.10

### Companion app

_No response_

### LINKED ISSUE #1379: Shake calibration doesn't work when sleep mode is enabled
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

when I raise my arm/wrist the watch doesn't wake up

### What should happen instead?

the watch should wake up

### Reproduction steps

Enable raise wrist in the settings
Switch the screen off with side button or wait for timeout
Move wrist in all sorts of angles and speeds

### More details?

Shake calibration also doesn't seem to register anything no matter how hard I shake 

The app with the gyro reads shows all movements correctly.

### Version

1.11

### Companion app

_No response_

### LINKED ISSUE #2271: Step notifications not working
### Verification

- [x] I searched for similar bug reports (including closed issues) and found none was relevant.

### What happened?

Gadgedbridge is using notification for the step characteristic but no steps are send by InfiniTime

### What should happen instead?

InfiniTime shoud send notifications on step changes

### Reproduction steps

Connect InfiniTime with Gadgedbridge

### More details?

Gadgedbridge's log file notes that it is using notifications for the steps-characteristic:
`
12:52:37.210 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 13. März um 12:52: NotifyAction on characteristic: 00030001-78fc-48fe-8e23-433b3a1942d0
12:52:37.211 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.NotifyAction - use NOTIFICATION for Characteristic 00030001-78fc-48fe-8e23-433b3a1942d0
12:52:37.212 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.NotifyAction - Successfully written characteristic 00030001-78fc-48fe-8e23-433b3a1942d0 descriptor
`

but no steps are reported. Only when turning on the display.

The steps sould be send to gadgedbridge emediently if notification is used.

### Version

v1.15.0 + main

### Companion app

Gadgedbridge

### PR DESCRIPTION
**Pull request by mark9064**
Polling the sensor every 100ms uses very little power, and handling out of date motion data causes excess complexity. This fixes correctness for reading (not notifications) steps/motion characteristics also
Closes #1379
Closes #1270
Closes #787
Closes #2268
Closes #2271
Closes #2272

### CODE REVIEW

File: src/systemtask/SystemTask.cpp [hunk 1]
```diff
@@ -429,18 +426,8 @@ void SystemTask::GoToSleep() {
 };
 
 void SystemTask::UpdateMotion() {
-  // Only consider disabling motion updates specifically in the Sleeping state
-  // AOD needs motion on to show up to date step counts
```
Comment (NeroBurner) [inline src/systemtask/SystemTask.cpp:433]: from the old comments it looks like the motion-hardware is in sleep mode when the watch is asleep. Wouldn't unconditionally update here fail when the chip is in sleep (or the SPI bus?)

Comment (mark9064) [reply src/systemtask/SystemTask.cpp:433]: Motion sensor is on the I2C bus which never gets slept. I think it used to be slept and that was removed some time ago

Comment (NeroBurner) [reply src/systemtask/SystemTask.cpp:433]: then there seems to be all in order 👍

**Review by NeroBurner — APPROVED** [review]

**Comment by mark9064** [comment]
Actually we can fix shake wake calibration as well. I'll push a new commit soon

**Comment by NeroBurner** [comment]
what do you mean with "(not notifications)" in your issue description?

**Comment by mark9064** [comment]
With the existing code, the motion values will be updated if anything is subscribed to notifications on the BLE characteristic, but it won't update it when a characteristic is only read. Sorry that wasn't super clear, I should've specified I meant BLE read/notify

**Comment by mark9064** [comment]
Removed the ShouldShakeWake method as a method which just did one comparison felt like overabstracting

**Comment by NeroBurner** [comment]
still looking good

**Comment by mark9064** [comment]
@geekbozu I remember you mentioned in the pinetime channel that you've got power measurement kit set up, could I take you up on your offer with this PR? :)

Testing configuration: digital watchface, sleep notification mode, all wake triggers disabled, BLE off, screen off
Refs to compare are:
https://github.com/InfiniTimeOrg/InfiniTime/pull/2328/commits/614440f51dca5634a53ceb92d0a51d13f139b89d (HEAD here)
https://github.com/InfiniTimeOrg/InfiniTime/commit/c1b9967d92269d9ad70a3d639f5bf915e83f4813 (current main)

Looking to know average power consumption in each configuration so we can decide if this PR is feasible

No worries at all if you're busy at the moment, just let me know somewhere

**Comment by mark9064** [comment]
Measurements are complete! Thanks so much taking a look Tim :)

With no BLE:

Main: 188μA ~= 40d idle
This PR: 210μA ~= 36d idle
So the change is ~22μA

I think this is a reasonable sacrifice given the complexity of working around it. In reality most the energy of the battery is consumed by screen on time, and BLE is on, so the impact to real usage is probably no more than 1 day in the worst case and a few hours in most cases.

**Comment by geekbozu** [comment]
Main Branch
image


This PR
image

Marks summary sums it up well!

**Comment by mark9064** [comment]
Going to merge soon unless any other comments :)

File: src/systemtask/SystemTask.cpp [hunk 2]
```diff
@@ -429,18 +426,8 @@ void SystemTask::GoToSleep() {
...
-  if (state == SystemTaskState::Sleeping && !(settingsController.isWakeUpModeOn(Pinetime::Controllers::Settings::WakeUpMode::RaiseWrist) ||
-                                              settingsController.isWakeUpModeOn(Pinetime::Controllers::Settings::WakeUpMode::Shake) ||
-                                              motionController.GetService()->IsMotionNotificationSubscribed())) {
```
Comment (mark9064) [inline src/systemtask/SystemTask.cpp:436]: Second I merged I realised this method can be removed... will draft a fixup soon

Comment (mark9064) [reply src/systemtask/SystemTask.cpp:436]: Opened #2352
