### PR TITLE
Heartrate app displays --- instead of 000

### LINKED ISSUE #1881: Heartrate Value jumps to 000
### Verification

- [X] I searched for similar bug reports (including closed issues) and found none was relevant.

### What happened?

The heartrate monitor will sporadically jump to 000, and will sometimes stay at that value. for a long time 

### What should happen instead?

_No response_

### Reproduction steps

Wearing the watch, I select the heart rate app and leave it running.

### More details?

_No response_

### Version

v1.13.0

### Companion app

Not currently paired with phone.

### PR DESCRIPTION
**Pull request by KaffeinatedKat**
Fixes #1881, when the heartrate data is not clear, or there is no measurement, display --- instead of 000

### CODE REVIEW

**Review by FintasticMan — APPROVED** [review]
I think this makes it more clear to the user what the situation is.

File: src/displayapp/screens/HeartRate.cpp [hunk 1]
```diff
@@ -82,10 +82,14 @@ void HeartRate::Refresh() {
     case Controllers::HeartRateController::States::NoTouch:
     case Controllers::HeartRateController::States::NotEnoughData:
       // case Controllers::HeartRateController::States::Stopped:
-      lv_label_set_text_static(label_hr, "000");
+      lv_label_set_text_static(label_hr, "---");
       break;
     default:
-      lv_label_set_text_fmt(label_hr, "%03d", heartRateController.HeartRate());
+      if (heartRateController.HeartRate() == 0) {
+        lv_label_set_text_static(label_hr, "---");
```
Comment (NeroBurner) [inline src/displayapp/screens/HeartRate.cpp:89]: is this last if-else needed? doesn't the state go back to `NotEnoughData`? Or does it go back down to 0 heartrate? I'm curious

Comment (FintasticMan) [reply src/displayapp/screens/HeartRate.cpp:89]: It does look like it goes to `NotEnoughData`, at least, if I let it get a value then remove it from my skin, it displays the not enough data text.

Comment (FintasticMan) [reply src/displayapp/screens/HeartRate.cpp:89]: I'm quite sure it's not needed.

Comment (KaffeinatedKat) [reply src/displayapp/screens/HeartRate.cpp:89]: it is in place so that when you press the stop button is displays "---" instead of "000", as this does not fall into the `NotEnoughData`

Comment (FintasticMan) [reply src/displayapp/screens/HeartRate.cpp:89]: Ah, thanks for the clarification!

**Review by NeroBurner — APPROVED** [review]
